# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitProfile < Formula
  desc "Git Profile allows to add and switch between multiple user profiles in git repositories"
  homepage "https://github.com/dotzero/git-profile"
  version "1.5.0"
  license "MIT"

  on_macos do
    url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_macOS-all.tar.gz"
    sha256 "46fbc4ee59b559dc0d1b82b242edcc36bb54c9871bbe71ab665dbda85b17e616"

    define_method(:install) do
      system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=#{version}")
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_Linux-amd64.tar.gz"
      sha256 "d4da39e53fb84c1fc169a6b1a3abdc2af220b8124eabf6880c56a33424d3cd2a"
      define_method(:install) do
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=#{version}")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_Linux-arm64.tar.gz"
      sha256 "9e0584429e72d1b5ceb3b4a8eb343bbc92327ea9372e8eb06e6e86eb460a621f"
      define_method(:install) do
        system "go", "build", *std_go_args(ldflags: "-s -w -X main.Version=#{version}")
      end
    end
  end
end
