# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitProfile < Formula
  desc "Git Profile allows to add and switch between multiple user profiles"
  homepage "https://github.com/dotzero/git-profile"
  version "1.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_macOS-amd64.tar.gz"
      sha256 "12770401b90d0552a0b30a2919fcc30836ebb71a2d023a6c85317c55187b3781"

      define_method(:install) do
        bin.install "git-profile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_macOS-arm64.tar.gz"
      sha256 "87bf61418131cdcabc0bd224b987ff6bfda7514f95b9c68ce458f04de9d7465a"

      define_method(:install) do
        bin.install "git-profile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_Linux-amd64.tar.gz"
      sha256 "90067763119ddfd1f81bcec5473c45c369ee2d343852ac24ce99bcf0dc968061"
      define_method(:install) do
        bin.install "git-profile"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dotzero/git-profile/releases/download/v1.5.0/git-profile_1.5.0_Linux-arm64.tar.gz"
      sha256 "9bb0c73fd5341f5e7ea8696532cc3d457d176901f699f32bd57919bb7d5f208b"
      define_method(:install) do
        bin.install "git-profile"
      end
    end
  end
end
