# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-profile" do
  name "git-profile"
  desc "Git Profile allows to add and switch between multiple user profiles in your git repositories"
  homepage "https://github.com/dotzero/git-profile"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-profile"

  on_macos do
    url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_macOS-all.tar.gz"
    sha256 "08232e49a16f658cab46b3f8a5376edfbd8ac4ed232bd015770519e6ccb27460"
  end

  on_linux do
    on_intel do
      url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_Linux-amd64.tar.gz"
      sha256 "c24ec07ae0939592f4cabea270a7a59dc68d8bac14d4d80c61dca7498d975add"
    end
    on_arm do
      url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_Linux-arm64.tar.gz"
      sha256 "e97d8e5d8b47c6122de81bb28ab6366022c46198e5f2c4a74b75ef59430c8c14"
    end
  end

  # No zap stanza required
end
