# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-profile" do
  version "1.8.0"

  on_macos do
    sha256 "c7cc2f875138c258531569dc5d921796d65c70e9b4d0ece30990d3bf03c6f6b9"
    url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_macOS-all.tar.gz"
  end

  on_linux do
    on_intel do
      sha256 "62b05d1a6f7557be7bf3dc8d394314507ba699f4991af1bebe5d59b4581b160d"
      url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_Linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "eeef47a9f6562f4b1c16f8a0ed4e8e4a2b0e3ba496e6881d196d8a75e73db3d5"
      url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_Linux-arm64.tar.gz"
    end
  end

  name "git-profile"
  desc "Git Profile allows to add and switch between multiple user profiles in your git repositories"
  homepage "https://github.com/dotzero/git-profile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-profile"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-profile"]
    end
  end

  # No zap stanza required

end
