# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-profile" do
  version "1.5.0"

  on_macos do
    url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_macOS-all.tar.gz"
    sha256 "2fb7487aeefd5b8607acc266ee795fee39d90c3b7edaa52fc912de1e10909323"
  end

  on_linux do
    on_intel do
      url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_Linux-amd64.tar.gz"
      sha256 "2b8c47d7da33155541912bf676feb99bee49daf67a26186681a1e817609fd64d"
    end
    on_arm do
      url "https://github.com/dotzero/git-profile/releases/download/v#{version}/git-profile_#{version}_Linux-arm64.tar.gz"
      sha256 "1291b25cada17423e016a227680c4c4093ce773946d7a59d796d242a3c9c9f2a"
    end
  end

  name "git-profile"
  desc "Git Profile allows to add and switch between multiple user profiles in your git repositories"
  homepage "https://github.com/dotzero/git-profile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-profile"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/restish"]
    end
  end

  # No zap stanza required

end
