# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitProfile < Formula
  desc "Git Profile allows to add and switch between multiple user profiles in your git repositories"
  homepage "https://github.com/dotzero/git-profile"
  version "1.4.0"

  on_macos do
    url "https://github.com/dotzero/git-profile/releases/download/v1.4.0/git-profile_1.4.0_macOS-all.tar.gz"
    sha256 "5b234ce6be68937f0be0d8fdc200b2aba825d6099c39adc72716a465527f55d3"

    def install
      bin.install "git-profile"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/dotzero/git-profile/releases/download/v1.4.0/git-profile_1.4.0_Linux-64bit.tar.gz"
      sha256 "912fdd1e7ce574257d692b0b66f9a30e5b65e9f20263d55f07477b979fa6133d"

      def install
        bin.install "git-profile"
      end
    end
  end

  test do
    system "#{bin}/git-profile version"
  end
end
